apps/noticias/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
    path('', views.home_noticias, name="h_noticias")
]

apps/usuarios/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='index'),
    path('contacto', views.contacto, name='contact'),
    path('noticias/', include('apps.noticias.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
]

apps/noticias/models.py
from django.db import models

# Create your models here.
# Esta herencia es la que va a ocupar el ORM
class Noticia(models.Model):
    titulo = models.CharField(max_length= 250)
    contenido = models.TextField()

    def __str__(self):
        return self.titulo

apps/usuarios/models.py
from django.db import models

# Create your models here.

apps/noticias/views.py
from django.shortcuts import render

# Create your views here.
def home_noticias(request):
    return render(request, 'noticias/home.html')

apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

def contacto(request):
    return render(request, 'contacto.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <title>Informatorio</title>
</head>

<body>
    <header>
        <nav>
            <h2>MENU</h2>
            <ul>
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'contact' %}">Contacto</a></li>
                <!--                nombre de la app : nombre de la url     -->
                <li><a href="{% url 'noticias:h_noticias' %}">Noticias</a></li>
            </ul>
        </nav>

        <img src="{% static 'img/dibu.jpg' %}" alt="">
    </header>
    <main>
        {% block contenido %}


        {% endblock contenido %}
    </main>
    <footer>

    </footer>
</body>

</html>

templates/contacto.html
{% extends 'base.html' %}

{% block contenido %}

<h1 class="titulo">CONTACT PAGE</h1>

{% endblock contenido %}

templates/home.html
{% extends 'base.html' %}

{% block contenido %}

<h1 class="titulo">HOME</h1>

{% endblock contenido %}

templates/noticias/home.html
{% extends 'base.html' %}


{% block contenido %}

    <h1>HOME NOTICIAS 👴</h1>

{% endblock contenido %}

templates/usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>